Remove the library() macro and _lib targets
jin/rules_maven pull request #16
Opened 2019-03-04 22:00 UTC by jin

(discussed with @davidsantiago)

The original motivation for adding _lib targets for every artifact was to ensure that you don't need to specify transitive dependencies on top of the top level artifact in `deps` in order to use the top level artifact. This is already fully wired up in the versionless aliases and the upstream java_import and aar_import targets.  

For example, if you want to use `junit:junit` and it depends on `org.hamcrest:hamcrest-core`, you do not need to specify `artifact("org.hamcrest:hamcrest-core")` alongside `artifact("junit:junit") in `deps`, because the `java_import` target for `junit:junit` already depends on `org:hamcrest:hamcrest-core`. 

The `library` macro, as it's implemented currently, re-exports the direct dependencies of an artifact, and itself, in a `java_library`. This may be useful to reduce the number of specified artifacts in `deps`, but it can hide unnecessary dependencies in the classpath, causing a large over-specification of required compile classes. If a target wishes to use an indirect dependency, the target should specify the versionless alias of the indirect dependency in its `deps`, and not rely on the overspecification of `_lib`/`library()` targets.

2019-03-04 22:00 UTC, jin commented
cc @davidsantiago

2019-03-04 23:29 UTC, davidsantiago commented
FWIW, LGTM. 🙈

2019-03-05 01:36 UTC, dkelmer requested changes
I want to make sure I understand: let's assume maven jar-A depends on maven jar-B. Before this change, projects could depend on the `_lib` target and then use symbols from both jar-A and jar-B? And what you're saying is that with this change, users would need to explicitly depend on jar-B if they wanted to use symbols from it? That definitely sounds like a step in the right direction. I eventually want to ban usage of jar-B entirely unless it's explicitly added to the `artifacts` list in the repository rule.

2019-03-05 01:36 UTC, dkelmer commented on README.md
> +which itself is wired up to dependencies specified in the artifact's POM file.
"which includes the transitive dependencies specified in the top level artifact's POM file"?

2019-03-05 19:14 UTC, jin commented
@dkelmer that is exactly right.

2019-03-06 21:18 UTC, dkelmer approved these changes

2019-03-06 21:31 UTC, merged